---
language: python
python: "2.7"
sudo: required

services:
  - docker

before_install:
  - docker build --rm --tag ferrarimarco/liquibase:latest .
script:
  - docker run --rm -it ferrarimarco/liquibase:latest
